name: build easy-mock

on:
  push:
    branches:
      - "dev"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCRORG }}
      - name: Build and push To GHCR
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/liubaicai/easy-mock:latest
